---
- name: Full Stack Application
  hosts: all
  become: yes
  tasks:
    - name: update_cache
      apt:
        update_cache: yes

- hosts: all
  become: true
  roles: 
    - database

- hosts: all
  become: true
  roles: 
    - backend

- hosts: all
  become: true
  roles: 
    - frontend
