---
- name: Install Apache2 on all nodes
  hosts: all
  become: yes
  tasks:
    # - name: Update the package index
    #   apt:
    #     update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Enable Apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Replacing the files
      copy:
        src: /home/einfochips/Tasks/Day16/index2.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: Restart the service
      service:
        name: apache2
        state: restarted